name = "fetc" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "UUID_STORAGE"
id = "4d2115c565d6402d891344b8e7e1c119"

[[routes]]
pattern = "bugwildcard.bmkg.xyz.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "bugwildcard.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.web.ndeso.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.web.bmkg.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.xvpn.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.gorengan.ndeso.web.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.gorengan.ndeso.web.id"
custom_domain = true

